name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Upload html test report
        run: action/upload-artifact@v2
#        with:
#          name: lint.html
#          path : app/build/reports/lint-results-debug.html

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
